name: Build and Test
on: [push]
jobs:
  androidTest:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Instrumentation Tests
        uses: denini08/shaker-action@v0.0.2.4
        with:
          api-level: 29
          arch: x86
          disable-animations: true
          script: ./gradlew connectedAndroidTest --stacktrace
