name: Build and Test
on: [push]
jobs:
  androidTest:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/checkout@v2
    - name: Instrumentation Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 28
        arch: x86
        disable-animations: false
        script: ./gradlew connectedAndroidTest --stacktrace
