name: Build and Test
on: [push]
jobs:
  androidTest:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86
          disable-animations: true
          script: free -h && (cat /proc/cpuinfo | grep processor | wc -l) #./gradlew connectedAndroidTest --stacktrace
